### ISSUE TITLE
Conceptnet API being down stops slide generation

### ISSUE THREAD

**Issue by h0h0h0** [korymath/talk-generator#15]
There was a small outage on Conceptnet Monday around noon ET. Slides did not generate. Creating issue for later fix. Worked around by waiting.

Stacktrace below:
```
~/projects/talk-generator/ $ python run.py --topic detroit --num_slides 10 --output_folder=./detroit/ --open_ppt=false
******************************************
Making 10 slide talk on: detroit
Traceback (most recent call last):
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 821, in <module>
    main(args)
  File "run.py", line 85, in main
    presenter=arguments.presenter)
  File "/Users/shaun/projects/talk-generator/presentation_schema.py", line 112, in generate_presentation
    seed_generator = self._seed_generator(topic, num_slides)
  File "/Users/shaun/projects/talk-generator/slide_topic_generators.py", line 38, in __init__
    fill_in_blank_topics_with_related(seeds)
  File "/Users/shaun/projects/talk-generator/slide_topic_generators.py", line 56, in fill_in_blank_topics_with_related
    _fill_in(seeds, i)
  File "/Users/shaun/projects/talk-generator/slide_topic_generators.py", line 72, in _fill_in
    related = conceptnet.get_weighted_related_words(neighbour, 200)
  File "/Users/shaun/projects/talk-generator/conceptnet.py", line 111, in get_weighted_related_words
    edges = _get_edges(word, cache_util.HashableDict(limit=limit))
  File "/Users/shaun/projects/talk-generator/conceptnet.py", line 90, in _get_edges
    return _get_data(word, arguments)["edges"]
  File "/Users/shaun/projects/talk-generator/conceptnet.py", line 83, in _get_data
    result = requests.get(url).json()
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/Users/shaun/projects/talk-generator/venv/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
(venv) :(  Mon Dec 03 12:24:25
~/projects/talk-generator/ $ 
```

**Comment by twinters** [comment]
ConceptNet is also really slowing down the whole slide generator significantly when it works properly, so we should probably find a backup option (that runs in parallel) in case it's out and slow in general. For most cases, we could probably switch to using Wikipedia links for related concepts, I'll try looking into it!

**Comment by korymath** [comment]
Minimal test:

```sh
import time
import requests

start = time.time()
obj = requests.get('http://api.conceptnet.io/c/en/example').json()
end = time.time()
print(end - start)
```

We should have a hard cap on slide generation times... so that we can ensure that the performance of the system will be within a certain time range.

**Comment by korymath** [comment]
Fixed with new parallel push in the works in dev.
