### ISSUE TITLE
Breaking Issue: JSONDecodeError

### ISSUE THREAD

**Issue by korymath** [korymath/talk-generator#51]
# Run code: 

```sh
talkgenerator --topic 'gardens' --num_slides 10
```

# Output:

```sh
2019-08-16 11:30:10,339 - talkgenerator - INFO - ******************************************
2019-08-16 11:30:10,339 - talkgenerator - INFO - Making 10 slide talk on: gardens
2019-08-16 11:30:10,733 - talkgenerator.conceptnet - INFO - Took 0.3449703459991724 seconds to poll Conceptnet for 'gardens'
Traceback (most recent call last):
  File "/Users/korymathewson/work/talk-generator/venv/bin/talkgenerator", line 11, in <module>
    load_entry_point('talkgenerator', 'console_scripts', 'talkgenerator')()
  File "/Users/korymathewson/work/talk-generator/talkgenerator/run.py", line 11, in main_cli
    main(args)
  File "/Users/korymathewson/work/talk-generator/talkgenerator/run.py", line 6, in main
    presentations, slide_deck = utils.generate_talk(args)
  File "/Users/korymathewson/work/talk-generator/talkgenerator/utils.py", line 63, in generate_talk
    parallel=args.parallel,
  File "/Users/korymathewson/work/talk-generator/talkgenerator/schema/presentation_schema.py", line 47, in generate_presentation
    seed_generator = self._seed_generator(topics, num_slides)
  File "/Users/korymathewson/work/talk-generator/talkgenerator/schema/slide_topic_generators.py", line 40, in __init__
    fill_in_blank_topics_with_related(seeds)
  File "/Users/korymathewson/work/talk-generator/talkgenerator/schema/slide_topic_generators.py", line 69, in fill_in_blank_topics_with_related
    _fill_in(seeds, i)
  File "/Users/korymathewson/work/talk-generator/talkgenerator/schema/slide_topic_generators.py", line 98, in _fill_in
    for word in related
  File "/Users/korymathewson/work/talk-generator/talkgenerator/schema/slide_topic_generators.py", line 99, in <listcomp>
    if not normalise_seed(word[1]) in seeds
  File "/Users/korymathewson/work/talk-generator/talkgenerator/schema/slide_topic_generators.py", line 117, in normalise_seed
    normalised = phrasefinder.get_rarest_word(normalised)
  File "/Users/korymathewson/work/talk-generator/talkgenerator/sources/phrasefinder.py", line 46, in get_rarest_word
    return min(words, key=lambda word: get_absolute_frequency_any_casing(word))
  File "/Users/korymathewson/work/talk-generator/talkgenerator/sources/phrasefinder.py", line 46, in <lambda>
    return min(words, key=lambda word: get_absolute_frequency_any_casing(word))
  File "/Users/korymathewson/work/talk-generator/talkgenerator/sources/phrasefinder.py", line 36, in get_absolute_frequency_any_casing
    absolute_frequencies = _get_absolute_frequencies(word)
  File "/Users/korymathewson/work/talk-generator/talkgenerator/sources/phrasefinder.py", line 17, in _get_absolute_frequencies
    pf_results = _search(word)
  File "/Users/korymathewson/work/talk-generator/talkgenerator/sources/phrasefinder.py", line 11, in _search
    result = requests.get(url).json()
  File "/Users/korymathewson/work/talk-generator/venv/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by twinters** [comment]
I had similar issues today. I think Phrasefinder might had issues earlier. I've added some additional checks for this in [https://github.com/korymath/talk-generator/commit/cb769433732bf27dc36d85e00547fe15faba87fa](https://github.com/korymath/talk-generator/commit/cb769433732bf27dc36d85e00547fe15faba87fa) and [https://github.com/korymath/talk-generator/commit/cefc23b21230900c813380dd3e61194cdd6a6baf](https://github.com/korymath/talk-generator/commit/cefc23b21230900c813380dd3e61194cdd6a6baf) to prevent this behaviour from happening in the future.
