### ISSUE TITLE
pixabay image source is broken

### ISSUE THREAD

**Issue by korymath** [korymath/talk-generator#70]
talkgenerator --topic "peanuts" --num_slides 10

```
Traceback (most recent call last):
  File "/Users/korymath/Documents/code/talk-generator/venv/bin/talkgenerator", line 33, in <module>
    sys.exit(load_entry_point('talkgenerator', 'console_scripts', 'talkgenerator')())
  File "/Users/korymath/Documents/code/talk-generator/venv/bin/talkgenerator", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/korymath/Documents/code/talk-generator/talkgenerator/run.py", line 1, in <module>
    from talkgenerator import generator
  File "/Users/korymath/Documents/code/talk-generator/talkgenerator/generator.py", line 13, in <module>
    from talkgenerator.schema.content_generators import full_name_generator
  File "/Users/korymath/Documents/code/talk-generator/talkgenerator/schema/content_generators.py", line 3, in <module>
    from talkgenerator.sources import pixabay, pexels
  File "/Users/korymath/Documents/code/talk-generator/talkgenerator/sources/pixabay.py", line 5, in <module>
    from pixabay import Image
ModuleNotFoundError: No module named 'pixabay'
```

**Comment by korymath** [comment]
Fixed with https://github.com/korymath/talk-generator/commit/9da8a641d374be4e7c4072e3eceef1c2a72bbd07
